import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create((theme) => ({
  container: { flex: 1, backgroundColor: theme.colors.background },
  flex: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.sm + 4,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1e1e48',
    backgroundColor: '#0a0a18',
  },
  headerBack: { padding: 4 },
  headerCenter: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 4 },
  headerAvatar: { width: 38, height: 38, borderRadius: 19 },
  headerAvatarPlaceholder: { backgroundColor: '#1e1e48', alignItems: 'center', justifyContent: 'center' },
  headerInfo: { marginLeft: 10, flex: 1 },
  headerNameRow: { flexDirection: 'row', alignItems: 'center' },
  headerName: { fontSize: 16, fontWeight: '700', color: '#EDEDFF' },
  headerStatus: { fontSize: 12, color: theme.colors.textSecondary, marginTop: 1 },
  headerMenuBtn: { padding: theme.spacing.sm },
  verifiedIcon: { marginLeft: 4 },
  chatArea: { flex: 1 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm + 4 },
  loadingText: { fontSize: 14, color: theme.colors.textSecondary },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#EDEDFF' },
  emptySub: { fontSize: 14, color: theme.colors.textSecondary },
  messageList: { paddingHorizontal: theme.spacing.sm + 4, paddingTop: theme.spacing.sm, paddingBottom: theme.spacing.md },
  messageRow: { flexDirection: 'row', alignItems: 'flex-end', marginBottom: 2 },
  messageRowMine: { justifyContent: 'flex-end' },
  messageRowTheirs: { justifyContent: 'flex-start' },
  messageRowSpaced: { marginTop: 10 },
  avatarSmall: { width: 24, height: 24, borderRadius: 12, marginRight: 6 },
  avatarSmallPlaceholder: { width: 24, height: 24, marginRight: 6 },
  bubbleWrap: { maxWidth: '75%', borderRadius: theme.radius.md + 8, padding: 10, paddingBottom: 6 },
  bubbleMine: { backgroundColor: '#6C63FF', borderBottomRightRadius: 4 },
  bubbleTheirs: { backgroundColor: '#111128', borderBottomLeftRadius: 4, borderWidth: 1, borderColor: '#1e1e48' },
  bubbleText: { fontSize: 15, lineHeight: 20, color: '#EDEDFF' },
  bubbleTextMine: { color: theme.colors.text },
  bubbleFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', marginTop: 4, gap: 2 },
  bubbleTime: { fontSize: 10, color: theme.colors.textSecondary },
  bubbleTimeMine: { color: 'rgba(255,255,255,0.6)' },
  readIcon: { marginLeft: 4 },
  imageBubble: { width: 200, height: 180, borderRadius: theme.radius.md - 4, marginTop: 4 },
  gifLabel: { position: 'absolute', top: 8, left: 8, fontSize: 9, fontWeight: '800', color: theme.colors.text, backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: theme.radius.sm, overflow: 'hidden' },
  voiceRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, paddingVertical: 4 },
  voiceWaveWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 2, height: 28 },
  voiceBar: { width: 3, borderRadius: 2 },
  voiceDuration: { fontSize: 11, color: theme.colors.textSecondary },
  voiceDurationMine: { color: 'rgba(255,255,255,0.7)' },
  pinnedBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 4 },
  pinnedText: { fontSize: 9, color: '#FFB347', fontWeight: '600' },
  reactionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.xs, marginTop: 6 },
  reactionChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(108,99,255,0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10 },
  reactionEmoji: { fontSize: 12 },
  reactionCount: { fontSize: 9, color: theme.colors.textSecondary, marginLeft: 2 },
  dateSeparator: { flexDirection: 'row', alignItems: 'center', marginVertical: theme.spacing.sm + 4, gap: theme.spacing.sm },
  dateSepLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: '#1e1e48' },
  dateSepText: { fontSize: 11, color: theme.colors.textSecondary, fontWeight: '600' },
  systemMessageWrap: { alignItems: 'center', marginVertical: theme.spacing.sm },
  systemMessageText: { fontSize: 12, color: theme.colors.textSecondary, fontStyle: 'italic' },
  inputBar: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: theme.spacing.sm, paddingVertical: 6, backgroundColor: '#0a0a18', borderTopWidth: 1, borderTopColor: '#1e1e48', gap: 4 },
  inputAction: { padding: theme.spacing.sm, alignItems: 'center', justifyContent: 'center' },
  inputWrap: { flex: 1, minHeight: 40, maxHeight: 120, backgroundColor: '#0d0d24', borderRadius: 20, paddingHorizontal: 14, paddingVertical: theme.spacing.sm, justifyContent: 'center', borderWidth: 1, borderColor: '#28285a' },
  inputField: { fontSize: 15, color: '#EDEDFF', maxHeight: 100, lineHeight: 20 },
  charCount: { fontSize: 10, color: theme.colors.textSecondary, textAlign: 'right', marginTop: 2 },
  sendBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#6C63FF', alignItems: 'center', justifyContent: 'center' },
  sendBtnDisabled: { backgroundColor: '#181834' },
  recordingWrap: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  recordingTimer: { fontSize: 13, color: theme.colors.error, fontWeight: '600', fontVariant: ['tabular-nums'] },
  recordingStop: { padding: 4 },
  uploadingBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm, paddingVertical: 6, backgroundColor: '#0a0a18' },
  uploadingText: { fontSize: 13, color: theme.colors.textSecondary },
  typingBar: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: theme.spacing.md, paddingVertical: 4, backgroundColor: '#0a0a18' },
  typingDots: { flexDirection: 'row', gap: 3 },
  typingDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#6C63FF' },
  typingText: { fontSize: 12, color: theme.colors.textSecondary, fontStyle: 'italic' },
  loadMoreIndicator: { marginVertical: theme.spacing.sm + 4 },
  scrollBtnWrap: { position: 'absolute', right: theme.spacing.md, bottom: theme.spacing.sm + 4 },
  scrollBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#111128', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#1e1e48' },
  scrollBtnBadge: { position: 'absolute', top: 2, right: 2, width: 8, height: 8, borderRadius: 4, backgroundColor: theme.colors.error },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(4,4,12,0.8)', justifyContent: 'center', alignItems: 'center' },
  menuOverlay: { position: 'absolute', top: 60, right: theme.spacing.sm + 4, zIndex: 100 },
  menuCard: { backgroundColor: '#111128', borderRadius: theme.radius.lg, padding: theme.spacing.sm, borderWidth: 1, borderColor: '#1e1e48', minWidth: 200, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.4, shadowRadius: 16, elevation: 16 },
  menuItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: theme.spacing.sm + 4, borderRadius: 10 },
  menuItemText: { fontSize: 14, color: '#EDEDFF', fontWeight: '500' },
  menuItemDanger: {},
  menuItemDangerText: { color: theme.colors.error },
  menuSeparator: { height: StyleSheet.hairlineWidth, backgroundColor: '#1e1e48', marginVertical: 4 },
  optionsCard: { backgroundColor: '#111128', borderRadius: theme.radius.lg, padding: theme.spacing.sm, borderWidth: 1, borderColor: '#1e1e48', minWidth: 180 },
  optionItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: theme.spacing.sm + 4, borderRadius: 10 },
  optionText: { fontSize: 14, color: '#EDEDFF', fontWeight: '500' },
  optionTextDanger: { color: theme.colors.error },
  reactionPickerCard: { flexDirection: 'row', backgroundColor: '#111128', borderRadius: 28, padding: theme.spacing.sm, borderWidth: 1, borderColor: '#1e1e48', gap: 4 },
  reactionPickItem: { padding: theme.spacing.sm },
  reactionPickEmoji: { fontSize: 28 },
  reportModal: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(4,4,12,0.9)' },
  reportCard: { backgroundColor: '#111128', borderRadius: 20, padding: theme.spacing.lg, width: '90%', maxWidth: 400, borderWidth: 1, borderColor: '#1e1e48', gap: theme.spacing.md },
  reportTitle: { fontSize: 18, fontWeight: '800', color: '#EDEDFF' },
  reportInput: { minHeight: 80, backgroundColor: '#0d0d24', borderRadius: theme.radius.md, padding: 14, fontSize: 15, color: '#EDEDFF', borderWidth: 1, borderColor: '#28285a', textAlignVertical: 'top' },
  reportBtns: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  reportCancel: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10 },
  reportCancelText: { fontSize: 14, color: theme.colors.textSecondary, fontWeight: '600' },
  reportSubmit: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10, backgroundColor: theme.colors.error },
  reportSubmitDisabled: { backgroundColor: '#181834' },
  reportSubmitText: { fontSize: 14, color: theme.colors.text, fontWeight: '700' },
  noteModal: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(4,4,12,0.9)' },
  noteCard: { backgroundColor: '#111128', borderRadius: 20, padding: theme.spacing.lg, width: '90%', maxWidth: 400, borderWidth: 1, borderColor: '#1e1e48', gap: theme.spacing.sm + 4 },
  noteTitle: { fontSize: 18, fontWeight: '800', color: '#EDEDFF' },
  noteInput: { minHeight: 100, backgroundColor: '#0d0d24', borderRadius: theme.radius.md, padding: 14, fontSize: 15, color: '#EDEDFF', borderWidth: 1, borderColor: '#28285a', textAlignVertical: 'top' },
  noteCount: { fontSize: 11, color: theme.colors.textSecondary, textAlign: 'right' },
  noteBtns: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  noteCancel: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10 },
  noteCancelText: { fontSize: 14, color: theme.colors.textSecondary, fontWeight: '600' },
  noteSave: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10, backgroundColor: '#6C63FF' },
  noteSaveDisabled: { backgroundColor: '#181834' },
  noteSaveText: { fontSize: 14, color: theme.colors.text, fontWeight: '700' },
  pinnedModal: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,4,12,0.9)' },
  pinnedCard: { backgroundColor: '#111128', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: theme.spacing.lg, maxHeight: '70%', borderWidth: 1, borderColor: '#1e1e48' },
  pinnedHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: theme.spacing.md },
  pinnedTitle: { fontSize: 18, fontWeight: '800', color: '#EDEDFF' },
  pinnedEmpty: { fontSize: 14, color: theme.colors.textSecondary, textAlign: 'center', marginVertical: theme.spacing.lg },
  pinnedList: {},
  pinnedItem: { backgroundColor: '#0d0d24', borderRadius: theme.radius.md, padding: 14, marginBottom: theme.spacing.sm, borderWidth: 1, borderColor: '#28285a' },
  pinnedItemText: { fontSize: 14, color: '#EDEDFF' },
  pinnedItemTime: { fontSize: 11, color: theme.colors.textSecondary, marginTop: 4 },
  videoPromptCard: { backgroundColor: '#111128', borderRadius: 20, padding: 28, width: '85%', maxWidth: 340, borderWidth: 1, borderColor: '#1e1e48', alignItems: 'center', gap: theme.spacing.md },
  videoPromptTitle: { fontSize: 18, fontWeight: '800', color: '#EDEDFF' },
  videoPromptSub: { fontSize: 14, color: theme.colors.textSecondary, textAlign: 'center' },
  videoPromptBtns: { flexDirection: 'row', gap: theme.spacing.md },
  videoBtn: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, backgroundColor: '#0d0d24', paddingHorizontal: 20, paddingVertical: 14, borderRadius: 14, borderWidth: 1, borderColor: '#28285a' },
  videoBtnText: { fontSize: 14, color: '#6C63FF', fontWeight: '600' },
  dateModal: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,4,12,0.9)' },
  dateCard: { backgroundColor: '#111128', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: theme.spacing.lg, maxHeight: '70%', borderWidth: 1, borderColor: '#1e1e48' },
  dateHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: theme.spacing.md },
  dateTitle: { fontSize: 18, fontWeight: '800', color: '#EDEDFF' },
  dateLoader: { marginVertical: 32 },
  dateIdeaItem: { backgroundColor: '#0d0d24', borderRadius: 14, padding: theme.spacing.md, marginBottom: 10, borderWidth: 1, borderColor: '#28285a' },
  dateIdeaVibe: { fontSize: 12, color: '#6C63FF', fontWeight: '700', marginBottom: 4 },
  dateIdeaText: { fontSize: 14, color: '#EDEDFF', lineHeight: 20 },
  dateRefreshBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: theme.spacing.sm + 4, marginTop: theme.spacing.sm },
  dateRefreshText: { fontSize: 14, color: '#6C63FF', fontWeight: '600' },
  previewModal: { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center' },
  previewClose: { position: 'absolute', top: 48, right: theme.spacing.md, zIndex: 10 },
  previewImage: { width: '100%', height: '80%' },
}));