/**
 * Privacy Policy screen — pure content definition.
 * All layout, styling, and navigation are handled by LegalDocument.
 */

import React from 'react';

import LegalDocument, {
  type LegalSection,
} from '../components/LegalDocument';

const LAST_UPDATED = 'April 2026';

const SECTIONS: readonly LegalSection[] = [
  {
    title: '1. Introduction',
    paragraphs: [
      'Welcome to MyArchetype ("we," "our," or "us"), operated by Elxan Huseynov ("Operator"). We are committed to protecting your privacy and personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application.',
      'By downloading and using MyArchetype, you agree to the collection and use of information in accordance with this policy. If you do not agree with the terms of this Privacy Policy, please do not access the application.',
    ],
  },
  {
    title: '2. Information We Collect',
    paragraphs: [
      'We collect information that you provide directly to us, information generated by your use of the app, and information from third-party sources:',
      {
        heading: 'Personal Information You Provide:',
        items: [
          'Name, age, and date of birth',
          'Email address',
          'Photos (taken via device camera only)',
          'Location (city/country, provided via device GPS or manual input)',
          'Physical attributes (height, body type)',
          'Personality quiz responses',
          'Religious views and lifestyle preferences',
        ],
      },
      {
        heading: 'Usage and Device Information:',
        items: [
          'App interactions (likes, matches, messages)',
          'Device information (OS, hardware model, device identifiers)',
          'Online status and last active time',
          'Crash reports and performance data',
          'IP address and general location data',
        ],
      },
      {
        heading: 'Information Derived from Photos (AI Processing):',
        items: [
          'Age estimation for verification purposes',
          'Identity verification via selfie matching',
          'Content moderation flags (inappropriate content detection)',
        ],
      },
    ],
  },
  {
    title: '3. Legal Basis for Processing (GDPR)',
    paragraphs: [
      'If you are in the European Economic Area (EEA), United Kingdom, or Switzerland, we process your data only when we have a legal basis to do so:',
      {
        items: [
          'Contractual Necessity: To create your account, provide matching services, and facilitate communication.',
          'Consent: To process sensitive data (e.g., religious views, physical attributes, biometric data for AI verification), send push notifications, and track analytics. You can withdraw consent at any time.',
          'Legitimate Interest: To ensure platform security, prevent fraud, moderate content, and improve our services.',
          'Legal Obligation: To comply with applicable laws, respond to legal processes, or enforce our terms.',
        ],
      },
    ],
  },
  {
    title: '4. How We Use Your Information',
    paragraphs: [
      'We use the information we collect for the following purposes:',
      {
        items: [
          'To create, manage, and verify your account',
          'To match you with compatible users and facilitate communication',
          'To verify your identity, estimate age, and prevent fraud/catfishing',
          'To moderate content and detect inappropriate behavior',
          'To improve our services, algorithms, and user experience',
          'To send notifications about matches, messages, and app updates',
          'To enforce our Terms of Service and maintain platform safety',
          'To conduct analytics and understand how users interact with the app',
        ],
      },
    ],
  },
  {
    title: '5. Photo Verification and AI Processing',
    paragraphs: [
      'We use AI-powered verification to process your photos. This involves processing biometric data (facial geometry) for a brief period to:',
      {
        items: [
          'Detect inappropriate or explicit content',
          'Estimate age for verification purposes',
          'Verify identity through selfie matching',
        ],
      },
      'Biometric data is processed securely in transit and at rest. We do not store raw biometric templates; this data is used solely for the immediate verification process and is deleted immediately after the verification decision is made. Your photos are stored encrypted on secure cloud servers.',
    ],
  },
  {
    title: '6. Data Sharing and Disclosure',
    paragraphs: [
      'We do not sell your personal data to third parties. We may share your information in the following circumstances:',
      {
        items: [
          'With Other Users: Your profile information (name, age, photos, etc.) is visible to matched users as part of the service.',
          'With Service Providers: Third-party vendors who perform services on our behalf (see Section 7).',
          'For Safety and Legal Reasons: If we believe disclosure is necessary to comply with law, protect our rights, prevent fraud, or ensure the safety of our users.',
          'Business Transfers: In connection with a merger, acquisition, or sale of assets, your data may be transferred to the acquiring entity.',
        ],
      },
    ],
  },
  {
    title: '7. Third-Party Services',
    paragraphs: [
      'We use the following third-party services that may have access to your information:',
      {
        items: [
          'Firebase (Google): Authentication, real-time database, analytics, and crash reporting. Privacy Policy: https://policies.google.com/privacy',
          'Cloudinary: Encrypted photo storage and processing. Privacy Policy: https://cloudinary.com/privacy',
          'DeepAI: AI content moderation and age estimation. Privacy Policy: https://deepai.org/terms-of-service',
          'Expo: Push notification delivery and app infrastructure. Privacy Policy: https://expo.dev/privacy',
        ],
      },
      'We require these third parties to use your data only as necessary to perform their services for us and in accordance with their own privacy policies.',
    ],
  },
  {
    title: '8. International Data Transfers',
    paragraphs: [
      'MyArchetype and our third-party service providers operate globally. If you are accessing the app from outside the United States, your information may be transferred to and processed in the United States or other countries. We ensure appropriate safeguards are in place, such as Standard Contractual Clauses (SCCs) approved by the European Commission, to protect your data during international transfers.',
    ],
  },
  {
    title: '9. Data Security',
    paragraphs: [
      'We implement robust security measures to protect your information:',
      {
        items: [
          'Messages are encrypted in transit and at rest using industry-standard protocols.',
          'Photos are stored on secure, encrypted cloud servers.',
          'We use Firebase Authentication for secure identity and access management.',
          'We restrict access to personal data to authorized personnel only.',
        ],
      },
      'However, no method of transmission over the Internet or electronic storage is 100% secure. While we strive to protect your personal data, we cannot guarantee its absolute security.',
    ],
  },
  {
    title: '10. Data Retention',
    paragraphs: [
      'We retain your data while your account is active. If you delete your account, we will permanently remove your primary profile data, including:',
      {
        items: [
          'Profile information and photos',
          'Match history and conversations',
          'Ratings and verification status',
        ],
      },
      'Please note that residual copies may remain in our backup systems for up to 90 days before being permanently purged. We may also retain anonymized, aggregated data that no longer identifies you for analytical purposes. We may retain certain data for longer periods if required by law or for legitimate legal or security needs.',
    ],
  },
  {
    title: '11. Cookies and Tracking Technologies',
    paragraphs: [
      'We and our third-party partners use cookies, device identifiers, and similar tracking technologies to:',
      {
        items: [
          'Maintain your logged-in session',
          'Analyze app usage and performance (e.g., Firebase Analytics)',
          'Deliver push notifications (e.g., Expo)',
        ],
      },
      'You can manage your device-level tracking preferences through your device settings (e.g., Limit Ad Tracking on iOS or Opt out of Ads Personalization on Android).',
    ],
  },
  {
    title: '12. Your Rights',
    paragraphs: [
      'Depending on your location, you may have the following rights regarding your personal data:',
      {
        items: [
          'Access: Request a copy of your personal data.',
          'Rectification: Correct inaccurate or incomplete data.',
          'Deletion: Request the deletion of your account and personal data.',
          'Restriction: Request that we restrict the processing of your data.',
          'Data Portability: Export your data in a structured, machine-readable format.',
          'Object: Object to our processing of your data based on legitimate interests.',
          'Withdraw Consent: Withdraw consent at any time where we rely on consent to process your data.',
          'Lodge a Complaint: Contact your local data protection authority (e.g., the ICO in the UK, or a DPA in the EU) if you believe your data rights have been violated.',
        ],
      },
      'To exercise any of these rights, contact us at privacy@myarchetype.app or use the in-app settings.',
    ],
  },
  {
    title: '13. California Privacy Rights (CCPA)',
    paragraphs: [
      'If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA):',
      {
        items: [
          'Right to Know: You have the right to request detailed information about the categories of data we collect, use, and share.',
          'Right to Delete: You have the right to request the deletion of your personal information.',
          'Right to Opt-Out of Sale: We do not sell your personal information, and we do not sell financial data or precise geolocation. No action is required to opt-out.',
          'Right to Non-Discrimination: We will not discriminate against you for exercising any of your CCPA rights.',
        ],
      },
    ],
  },
  {
    title: '14. Children\'s Privacy',
    paragraphs: [
      'MyArchetype is intended for users 18 years of age and older. We do not knowingly collect information from anyone under 18. If we discover that a user under 18 has created an account, their account will be immediately terminated and their data deleted. If you believe a minor is using the app, please contact us immediately.',
    ],
  },
  {
    title: '15. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page, updating the "Last Updated" date, and providing an in-app notification or email prior to the changes taking effect. Your continued use of the app after the changes constitute your acceptance of the updated policy.',
    ],
  },
  {
    title: '16. Contact Us & Entity Information',
    paragraphs: [
      'This service is operated by:',
      'Elxan Huseynov',
      'Yeni Guneshli, Surakhani District',
      'Baku, Azerbaijan',
      '',
      'For questions about this Privacy Policy or to exercise your data rights, contact our Data Protection Officer at:',
      'Email: privacy@myarchetype.app',
      'We will respond to your request within 30 days.',
    ],
  },
];

export default function PrivacyPolicyScreen() {
  return (
    <LegalDocument
      title="Privacy Policy"
      lastUpdated={LAST_UPDATED}
      sections={SECTIONS}
      footerText="By using MyArchetype, you agree to this Privacy Policy."
    />
  );
}