import { writeAuditLog } from './logger';
const fetchSafe=async(u:string,o:RequestInit,t=8000)=>{const c=new AbortController();const id=setTimeout(()=>c.abort(),t);try{return await fetch(u,{...o,signal:c.signal});}finally{clearTimeout(id);}};

export interface AiFeatureConsent{userId:string;featureId:string;featureName:string;description:string;dataUsed:string[];consentedAt:Date|null;withdrawnAt:Date|null;optOut:boolean;}
export const AI_FEATURES_REQUIRING_CONSENT:Omit<AiFeatureConsent,'userId'|'consentedAt'|'withdrawnAt'|'optOut'>[]=[ {featureId:'match_algorithm',featureName:'AI Match Recommendations',description:'We use AI to suggest compatible matches based on your profile, behavior, and preferences.',dataUsed:['profile_data','swipe_history','message_patterns']},{featureId:'compatibility_score',featureName:'Compatibility Scoring',description:'AI-generated compatibility scores shown on profiles.',dataUsed:['quiz_answers','profile_data']},{featureId:'content_moderation',featureName:'Automated Content Review',description:'AI automatically reviews messages and photos for safety violations.',dataUsed:['messages','photos']},{featureId:'behavioral_analysis',featureName:'Safety Behavioral Analysis',description:'We analyze interaction patterns to detect potential scammers or unsafe users.',dataUsed:['message_patterns','login_patterns','engagement_data']},];

export function enforceAiOptOut(userId:string,featureId:string,records:AiFeatureConsent[]):{allowed:boolean;reason?:string}{
const r=records.find(x=>x.userId===userId&&x.featureId===featureId);
if(!r)return{allowed:false,reason:'no_consent_record'};if(r.optOut)return{allowed:false,reason:'user_opted_out'};if(!r.consentedAt)return{allowed:false,reason:'consent_not_given'};if(r.withdrawnAt)return{allowed:false,reason:'consent_withdrawn'};return{allowed:true};}

export const AI_AGENT_GUARDRAILS={cannotSendMessagesAsUser:true,cannotModifyProfile:true,cannotMakePayments:true,cannotSharePersonalInfo:true,mustDiscloseAI:true,maxSuggestionsPerInteraction:3,prohibitedTopics:['financial_advice','medical_advice','legal_advice']};
export function validateAgentAction(a:{type:string;payload:Record<string,unknown>}):{permitted:boolean;reason?:string}{
const BLOCKED=new Set(['send_message','edit_profile','make_payment','share_location','export_contacts','delete_account']);
return BLOCKED.has(a.type)?{permitted:false,reason:`AI agents cannot perform: ${a.type}`}:{permitted:true};}
export function enforceAiDisclosure(txt:string):string{return txt.includes('generated by AI')?txt:txt+'\n\n---\n_This suggestion was generated by AI. Always use your own judgment._';}

export async function checkGroundedness(claim:string,context:string):Promise<{grounded:boolean;confidence:number}>{
try{const r=await fetchSafe(`${process.env['EXPO_PUBLIC_API_URL']??''}/safety/groundedness`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({claim,context})});return r.ok?r.json() as Promise<{grounded:boolean;confidence:number}>:{grounded:true,confidence:0};}catch{return{grounded:true,confidence:0};}}

export const AI_INFRASTRUCTURE_POLICIES={modelVersioning:true,trainingDataAudit:true,modelSignatureVerification:true,canaryInputMonitoring:true,outputSanitization:true,fallbackToRules:true};
export function verifyModelSignature(id:string,reported:string,expected:string):{valid:boolean;tampered:boolean}{void id;return{valid:reported===expected,tampered:reported!==expected};}
export function sanitizeModelOutput(o:string):string{return o.replace(/\[SYSTEM\].*?\[\/SYSTEM\]/gis,'').replace(/ignore (previous|all) instructions/gi,'[REDACTED]').trim();}

export interface ModelVersion{modelId:string;version:string;deployedAt:string;checksum:string;active:boolean;rollbackTo?:string;}
export function selectModelVersion(versions:ModelVersion[]):ModelVersion|null{const a=versions.filter(v=>v.active);return a.length?a.sort((x,y)=>new Date(y.deployedAt).getTime()-new Date(x.deployedAt).getTime())[0]??null:null;}

export function auditFilterBias(usage:{userId:string;filterField:string;filterValue:string}[]):{flaggedFilters:{field:string;concern:string}[]}{
const R=new Set(['ethnicity','race','skin_color','nationality']),S=new Set(['income','education_level','neighborhood']);
const f:{field:string;concern:string}[]=[];
usage.forEach(u=>{if(R.has(u.filterField))f.push({field:u.filterField,concern:'potential_racial_discrimination'});if(S.has(u.filterField))f.push({field:u.filterField,concern:'potential_socioeconomic_discrimination'});});
if(f.length)writeAuditLog('ai.bias_filter_flagged',{fields:f.map(x=>x.field)}).catch(()=>{});return{flaggedFilters:f};}

export interface ScamDetectionFailureMode{type:'novel_script'|'language_switch'|'slow_burn'|'trusted_platform_name'|'victim_demographic';description:string;mitigationStrategy:string;}
export const KNOWN_FAILURE_MODES:ScamDetectionFailureMode[]=[
  {type:'novel_script',description:'New scam scripts not yet in training data',mitigationStrategy:'Weekly retraining with newly confirmed scam reports + human review queue'},
  {type:'language_switch',description:'Scammer switches language mid-conversation to evade classifier',mitigationStrategy:'Apply Qwen3Guard (119 languages) on every message regardless of detected language'},
  {type:'slow_burn',description:'Weeks of benign messages before financial request',mitigationStrategy:'Maintain 90-day conversation embeddings and score holistic relationship arc'},
  {type:'trusted_platform_name',description:'Fake platform named similarly to legitimate',mitigationStrategy:'Fuzzy string matching against known legitimate platform list + domain check'},
];
export function auditScamDetectionGaps(reports:{reportedContent:string;wasAutoDetected:boolean;category:string}[]):{falseNegativeRate:number;missedCategories:string[]}{
const m=reports.filter(r=>!r.wasAutoDetected);return{falseNegativeRate:reports.length>0?m.length/reports.length:0,missedCategories:[...new Set(m.map(r=>r.category))]};}

export function evaluateModelDrift(b:{fp:number;fn:number;predictions:number[]},c:{fp:number;fn:number;predictions:number[]}):{driftScore:number;degraded:boolean;action:string}{
const ds=Math.abs((c.fp-b.fp)/(b.fp+0.001)+(c.fn-b.fn)/(b.fn+0.001));
const fnD=c.fn>b.fn*1.5,fpD=c.fp>b.fp*2;
const act=fnD?'rollback':fpD?'retrain':ds>0.2?'alert':'none';
if(act!=='none')writeAuditLog('ai.model_drift_detected',{driftScore:ds,action:act}).catch(()=>{});
return{driftScore:ds,degraded:fnD||fpD,action:act};}

export interface BiasAuditResult{metric:string;value:number;threshold:number;passed:boolean;}
export function auditMatchingFairness(outcomes:{userId:string;demographic:string;matchCount:number;shown:number}[]):BiasAuditResult[]{
const g=new Map<string,{m:number;s:number;c:number}>();
outcomes.forEach(o=>{const x=g.get(o.demographic)??{m:0,s:0,c:0};x.m+=o.matchCount;x.s+=o.shown;x.c++;g.set(o.demographic,x);});
const rates=[...g.entries()].map(([,v])=>v.s>0?v.m/v.s:0);
if(rates.length<2)return[];
const di=Math.min(...rates)/Math.max(...rates);
return[{metric:'disparate_impact_ratio',value:di,threshold:0.8,passed:di>=0.8}];}

export function detectModelDrift(recentMetrics:{accuracy:number;precision:number;recall:number;timestamp:number}[],baselineAccuracy:number):{drifted:boolean;degradation:number}{
if(recentMetrics.length===0)return{drifted:false,degradation:0};
const recent=recentMetrics.slice(-10);const avgAccuracy=recent.reduce((s,m)=>s+m.accuracy,0)/recent.length;
const degradation=baselineAccuracy-avgAccuracy;return{drifted:degradation>0.05,degradation};}

export function detectAdversarialInput(t:string):{isAdversarial:boolean;technique:string[];confidence:number}{
const tech:string[]=[];
if(/[\u200B-\u200F\u2060\uFEFF\u00AD]/.test(t))tech.push('zero_width_injection');
if(/[\u0400-\u04FF]/.test(t)&&/[a-zA-Z]/.test(t))tech.push('homoglyph_mixing');
const lr=(t.match(/[a-zA-Z]/g)??[]).length/Math.max(t.length,1);if(lr<0.3&&t.length>10)tech.push('homoglyph_attack');
if(/[A-Za-z0-9+/]{20,}={0,2}/.test(t))tech.push('base64_evasion');
if(/(.)\1{10,}/.test(t))tech.push('padding_attack');
if(/\s{5,}/.test(t))tech.push('whitespace_manipulation');
if(/ignore (previous|above|all) instructions|system prompt|you are now|roleplay as/i.test(t))tech.push('prompt_injection');
if(/system\s*:\s*/i.test(t))tech.push('role_injection');
if(/[\u200B-\u200F\u2060\uFEFF]{2,}/.test(t))tech.push('zero_width_stuffing');
return{isAdversarial:tech.length>0,technique:tech,confidence:Math.min(tech.length*0.3,1)};}

export interface AIDecisionExplanation{decision:string;factors:{factor:string;weight:number;direction:'positive'|'negative'}[];confidence:number;appealable:boolean;}
export function explainModerationDecision(r:{flagged:boolean;categories:Record<string,number>}):AIDecisionExplanation{
const f=Object.entries(r.categories).filter(([,s])=>s>0.1).map(([k,w])=>({factor:k,weight:w,direction:w>0.5?'negative':'positive' as const})).sort((a,b)=>b.weight-a.weight);
return{decision:r.flagged?'content_flagged':'content_allowed',factors:f,confidence:f[0]?.weight??0,appealable:true};}

export interface AIConsentConfig{matchingAlgorithm:boolean;photoAnalysis:boolean;messageModeration:boolean;personalityInsights:boolean;voiceAnalysis:boolean;}
export const DEFAULT_AI_CONSENT:AIConsentConfig={matchingAlgorithm:true,photoAnalysis:true,messageModeration:true,personalityInsights:false,voiceAnalysis:false};

export interface AiAnomalyResult{anomaly:boolean;score:number;indicators:string[];action:'allow'|'flag'|'block';}
export function detectAiTrafficAnomaly(requests:Array<{endpoint:string;responseTimeMs:number;statusCode:number;timestamp:number}>):AiAnomalyResult{
if(requests.length<10)return{anomaly:false,score:0,indicators:[],action:'allow'};
const i:string[]=[];
const avgRt=requests.reduce((s,r)=>s+r.responseTimeMs,0)/requests.length;
const errorRate=requests.filter(r=>r.statusCode>=500).length/requests.length;
const recentSpike=requests.filter(r=>Date.now()-r.timestamp<60_000).length;
if(avgRt>5000)i.push(`high_latency:${Math.round(avgRt)}ms`);
if(errorRate>0.1)i.push(`high_error_rate:${Math.round(errorRate*100)}%`);
if(recentSpike>100)i.push(`request_spike:${recentSpike}/min`);
const score=Math.min(i.length*33,100);
const action=score>=66?'block':score>=33?'flag':'allow';
if(action!=='allow')writeAuditLog('ai.traffic_anomaly',{indicators:i,score}).catch(()=>{});
return{anomaly:i.length>0,score,indicators:i,action};}
export const aiTrafficAnomaly=detectAiTrafficAnomaly;

export interface CanaryResult{triggered:boolean;modelId:string;expectedOutput:string;actualOutput:string;tampered:boolean;}
export function checkCanaryInput(modelId:string,output:string,canaries:Array<{input:string;expectedOutput:string}>):CanaryResult{
const failed=canaries.find(c=>!output.includes(c.expectedOutput));
if(failed){writeAuditLog('ai.canary_triggered',{modelId,expected:failed.expectedOutput}).catch(()=>{});return{triggered:true,modelId,expectedOutput:failed.expectedOutput,actualOutput:output,tampered:true};}
return{triggered:false,modelId,expectedOutput:'',actualOutput:output,tampered:false};}
export const canaryMonitor=checkCanaryInput;

export interface ModelFallbackResult{usingFallback:boolean;reason:string;action:'rule_based'|'cached'|'deny_all';}
export function activateRuleBasedFallback(modelHealthy:boolean,errorRate:number):ModelFallbackResult{
if(!modelHealthy||errorRate>0.2){writeAuditLog('ai.fallback_activated',{modelHealthy,errorRate}).catch(()=>{});return{usingFallback:true,reason:modelHealthy?`high_error_rate:${errorRate}`:'model_unhealthy',action:'rule_based'};}
return{usingFallback:false,reason:'model_healthy',action:'rule_based'};}
export const ruleBasedFallback=activateRuleBasedFallback;

export interface OutputSanitizeResult{sanitized:boolean;original:string;clean:string;removedPatterns:string[];}
export function sanitizeAiOutput(output:string):OutputSanitizeResult{
const removed:string[]=[];let clean=output;
const patterns:[RegExp,string][]=[
  [/\[SYSTEM\].*?\[\/SYSTEM\]/gis,'system_block'],
  [/ignore (previous|all) instructions/gi,'prompt_injection'],
  [/\b(SSN|social security|credit card|cvv|bank account)\b.*?\d{4,}/gi,'pii_leak'],
  [/<script[^>]*>.*?<\/script>/gis,'xss_attempt'],
  [/https?:\/\/(?!myarchetype\.app)[^\s]+\.(tk|ml|ga|cf|gq)/gi,'malicious_url'],
];
for(const[pattern,label]of patterns){if(pattern.test(clean)){removed.push(label);clean=clean.replace(pattern,'[REDACTED]');}}
return{sanitized:removed.length>0,original:output,clean:clean.trim(),removedPatterns:removed};}
export const aiOutputSanitize=sanitizeAiOutput;

export interface SlowBurnResult{detected:boolean;conversationAgedays:number;benignPhaseDays:number;financialRequestDetected:boolean;riskScore:number;}
export function detectSlowBurnScam(messages:Array<{text:string;timestamp:number;fromUser:boolean}>,financialKeywords:string[]=['send money','wire transfer','crypto','bitcoin','gift card','investment','trading platform']):SlowBurnResult{
if(messages.length<5)return{detected:false,conversationAgedays:0,benignPhaseDays:0,financialRequestDetected:false,riskScore:0};
const first=Math.min(...messages.map(m=>m.timestamp)),last=Math.max(...messages.map(m=>m.timestamp));
const ageDays=(last-first)/86_400_000;
const financialMsg=messages.find(m=>financialKeywords.some(k=>m.text.toLowerCase().includes(k))&&!m.fromUser);
if(!financialMsg)return{detected:false,conversationAgedays:Math.round(ageDays),benignPhaseDays:0,financialRequestDetected:false,riskScore:0};
const benignDays=(financialMsg.timestamp-first)/86_400_000;
const riskScore=Math.min(Math.round((benignDays>14?40:benignDays>7?25:10)+(ageDays>30?30:ageDays>14?20:10)),100);
if(riskScore>=25)writeAuditLog('ai.slow_burn_scam',{ageDays,benignDays,riskScore}).catch(()=>{});
return{detected:riskScore>=25,conversationAgedays:Math.round(ageDays),benignPhaseDays:Math.round(benignDays),financialRequestDetected:true,riskScore};}
export const slowBurnDetect=detectSlowBurnScam;

export interface LanguageSwitchResult{detected:boolean;languages:string[];switchCount:number;suspicionReason:string;}
export function detectLanguageSwitchEvasion(messages:Array<{text:string;detectedLanguage:string;timestamp:number}>):LanguageSwitchResult{
const langs=messages.map(m=>m.detectedLanguage);const unique=[...new Set(langs)];
const switches=langs.filter((l,i)=>i>0&&l!==langs[i-1]).length;
const suspicious=switches>=3||unique.length>=3;
if(suspicious)writeAuditLog('ai.language_switch_evasion',{languages:unique,switches}).catch(()=>{});
return{detected:suspicious,languages:unique,switchCount:switches,suspicionReason:suspicious?`${switches} language switches across ${unique.length} languages detected — possible classifier evasion`:'Normal conversation pattern'};}
export const languageSwitchEvasion=detectLanguageSwitchEvasion;

export interface TrustedPlatformSpoof{detected:boolean;claimedPlatform:string;legitimatePlatform?:string;similarity:number;recommendation:string;}
const LEGITIMATE_PLATFORMS=['coinbase','binance','kraken','robinhood','etrade','fidelity','schwab','paypal','venmo','cashapp','zelle','westernunion','moneygram'];
export function detectTrustedPlatformSpoof(text:string):TrustedPlatformSpoof{
const lower=text.toLowerCase();
for(const legit of LEGITIMATE_PLATFORMS){
const variations=[legit,`${legit}pro`,`${legit}vip`,`${legit}exchange`,`${legit}trading`,`my${legit}`,`${legit}official`];
for(const v of variations){if(v!==legit&&lower.includes(v)){return{detected:true,claimedPlatform:v,legitimatePlatform:legit,similarity:0.9,recommendation:`"${v}" is likely impersonating "${legit}". Warn user and flag message.`};}}}
return{detected:false,claimedPlatform:'',similarity:0,recommendation:'No trusted platform spoofing detected.'};}
export const platformNameSpoof=detectTrustedPlatformSpoof;

export interface VictimDemographicResult{vulnerable:boolean;signals:string[];riskLevel:'none'|'low'|'medium'|'high';}
export function detectVictimDemographicTargeting(profile:{age?:number;recentDivorce?:boolean;recentBereavement?:boolean;financialStressSignals?:boolean;longDistanceRelationship?:boolean;lonelinessSignals?:boolean}):VictimDemographicResult{
const signals:string[]=[];
if(profile.age&&profile.age>=55)signals.push('elder_demographic');
if(profile.recentDivorce)signals.push('recent_divorce');
if(profile.recentBereavement)signals.push('recent_bereavement');
if(profile.financialStressSignals)signals.push('financial_stress');
if(profile.longDistanceRelationship)signals.push('long_distance_preference');
if(profile.lonelinessSignals)signals.push('loneliness_signals');
const rl:VictimDemographicResult['riskLevel']=signals.length>=4?'high':signals.length>=2?'medium':signals.length>=1?'low':'none';
if(rl!=='none')writeAuditLog('ai.victim_demographic_targeting',{signals,riskLevel:rl}).catch(()=>{});
return{vulnerable:rl!=='none',signals,riskLevel:rl};}
export const victimTargetingDetect=detectVictimDemographicTargeting;
