type Severity = 'low' | 'medium' | 'high' | 'critical';

interface DetectorDef {
  id: number;
  section: string;
  name: string;
  severity: Severity;
  patterns: readonly string[];
  enabled: boolean;
  detect(input: string): boolean;
}

function makeDet(id: number, section: string, name: string, severity: Severity, patterns: string[]): DetectorDef {
  return {
    id, section, name, severity, patterns, enabled: true,
    detect(input: string) { return patterns.some(p => input.includes(p)); },
  };
}

export const _det771 = makeDet(771, '1.8', 'AI nudification output detection', 'critical', ['nudificationDetect', 'aiNudification', 'clothesRemoval']);
export const _det120 = makeDet(120, '2.2', 'Sexual solicitation', 'high', ['sexual_solicitation', 'SEXUAL_PATTERNS', 'sexualSolicitation', 'detectSexualSolicitation']);
export const _det886 = makeDet(886, '2.2', 'Sugar arrangement language', 'medium', ['sugarArrangement', 'arrangement_language']);
export const _det887 = makeDet(887, '2.2', 'Verification fee scam', 'high', ['verificationFee', 'payToVerify', 'sendMoney.*verify']);
export const _det888 = makeDet(888, '2.2', 'Escort/sex work solicitation', 'high', ['escortSolicitation', 'sexWork', 'companionship.*fee']);
export const _det889 = makeDet(889, '2.2', 'Paid companionship emoji patterns', 'medium', ['paidCompanionEmoji', 'roses.*emoji']);
export const _det891 = makeDet(891, '2.2', 'Coded pricing language', 'medium', ['codedPricing', 'priceCode', 'roses.*hundred']);
export const _det892 = makeDet(892, '2.2', 'Third-party controlled profile', 'critical', ['controlledProfile', 'pimpControl', 'thirdPartyProfile']);
export const _det194 = makeDet(194, '2.7', 'Embedded phone numbers', 'medium', ['contact_info_phone', 'PHONE_REGEX', 'extractPhoneNumbers']);
export const _det209 = makeDet(209, '2.8', 'Strip zero-width characters', 'medium', ['stripZWChars', 'removeZeroWidth']);
export const _det211 = makeDet(211, '2.8', 'Zalgo / glitch text detection', 'medium', ['zalgo', 'glitchText', 'combiningCharacters']);
export const _det212 = makeDet(212, '2.8', 'Base64 encoded content', 'medium', ['base64Detect', 'encodedContent', 'base64Pattern']);
export const _det216 = makeDet(216, '2.8', 'Translation artifact detection', 'low', ['translationArtifact', 'machineTranslation', 'unnaturalPhrasing']);
export const _det218 = makeDet(218, '2.8', 'Message entropy analysis', 'low', ['messageEntropy', 'shannonEntropy', 'entropyScore']);
export const _det219 = makeDet(219, '2.8', 'Readability score anomaly', 'low', ['readabilityScore', 'fleschKincaid', 'readingLevel']);
export const _det227 = makeDet(227, '2.9', 'Time zone inconsistency', 'medium', ['timezoneInconsistency', 'timeZoneMismatch', 'messagingHours']);
export const _det330 = makeDet(330, '5.4', 'Stalking via profile views', 'high', ['trackProfileView', 'profileView.*suspicious', 'excessiveViews']);
export const _det333 = makeDet(333, '5.4', 'Elo / ranking manipulation', 'medium', ['detectEloManipulation', 'eloManipul', 'scoreManipul']);
export const _det337 = makeDet(337, '5.4', 'Super like abuse', 'low', ['checkSuperLikeLimit', 'superLikeLimit', 'superLikeAbuse']);
export const _det338 = makeDet(338, '5.4', 'Bot story views', 'medium', ['detectBotStoryViews', 'botStoryView', 'botViewStory']);
export const _det340 = makeDet(340, '5.4', 'Swipe pattern anomalies', 'medium', ['swipeAnomaly', 'likesEveryone', 'swipeRatio']);
export const _det343 = makeDet(343, '5.4', 'Conversion fraud', 'medium', ['detectConversionFraud', 'conversionFraud', 'fraudConversion']);
export const _det769 = makeDet(769, '5.6', 'Trafficking victim referral pathway', 'critical', ['traffickingReferral', 'victimPathway', 'polarisTipline']);
export const _det739 = makeDet(739, '5.7', 'Ex-partner profile monitoring', 'high', ['exPartnerMonitoring', 'exStalking', 'exProfileView']);
export const _det741 = makeDet(741, '5.7', 'Post-breakup impersonation', 'high', ['postBreakupImpersonation', 'exImpersonation']);
export const _det742 = makeDet(742, '5.7', 'Coordinated friend-group harassment', 'high', ['coordinatedHarassment', 'friendGroupAttack']);
export const _det789 = makeDet(789, '5.8', 'Parent-created profile for adult', 'medium', ['parentCreatedProfile', 'thirdPartyProfileOp']);
export const _det824 = makeDet(824, '5.10', 'State-sponsored honeytrap pattern', 'high', ['honeytrapPattern', 'stateSponsored', 'espionagePattern']);
export const _det380 = makeDet(380, '7', 'NSFW speech in voice intros', 'high', ['checkNsfwSpeechVoice', 'nsfw_speech_voice']);
export const _det387 = makeDet(387, '7', 'Emotional authenticity scoring', 'low', ['emotionalAuthenticity', 'emotionAnalysis', 'sentimentVoice']);
export const _det392 = makeDet(392, '7', 'DTMF tone detection', 'medium', ['dtmfDetect', 'toneDetect', 'touchtone']);
export const _det394 = makeDet(394, '7', 'Echo / delay pattern detection', 'low', ['echoDetect', 'delayPattern', 'latencyAnomaly']);
export const _det425 = makeDet(425, '10', 'Trust score decay', 'medium', ['scoreDecay', 'applyTrustDecay', 'trustDecay']);
export const _det428 = makeDet(428, '10', 'Shadow ban system', 'medium', ['shadowBan', 'silentRestrict', 'hiddenBan']);
export const _det436 = makeDet(436, '10', 'False positive rate tracking', 'medium', ['falsePositiveRate', 'fprTracking', 'detectorAccuracy']);
export const _det437 = makeDet(437, '10', 'Inter-rater reliability', 'medium', ['interRater', 'cohensKappa', 'raterAgreement']);
export const _det798 = makeDet(798, '10.1', 'Inactive profile reactivation consent', 'medium', ['reactivationConsent', 'zombieProfile']);
export const _det799 = makeDet(799, '10.1', 'Deceased user account detection', 'medium', ['deceasedUser', 'memorialAccount', 'deathNotification']);
export const _det800 = makeDet(800, '10.1', 'Ghost profile inflation audit', 'medium', ['profileInflation', 'ghostAudit', 'activeUserCount']);
export const _det864 = makeDet(864, '10.2', 'Litigation risk scoring', 'medium', ['litigationRisk', 'legalRisk', 'riskScore.*legal']);
export const _det440 = makeDet(440, '11', 'Instagram profile exists', 'low', ['checkInstagramProfileExists', 'checkInstagram']);
export const _det441 = makeDet(441, '11', 'Spotify URL format', 'low', ['validateSpotifyUrl', 'validateSpotify']);
export const _det442 = makeDet(442, '11', 'TikTok URL format', 'low', ['validateTikTokUsername', 'validateTikTok']);
export const _det443 = makeDet(443, '11', 'LinkedIn URL format', 'low', ['validateLinkedInUrl', 'validateLinkedIn']);
export const _det444 = makeDet(444, '11', 'Username consistency check', 'medium', ['checkUsernameConsistency', 'usernameConsistency']);
export const _det445 = makeDet(445, '11', 'Cross-platform handle consistency', 'medium', ['crossPlatformConsistency', 'handleConsistency']);
export const _det446 = makeDet(446, '11', 'Social account age check', 'medium', ['socialAccountAge', 'accountCreationDate']);
export const _det447 = makeDet(447, '11', 'Social follower count plausibility', 'medium', ['followerPlausibility', 'followerCount', 'followersCheck']);
export const _det448 = makeDet(448, '11', 'Social account activity recency', 'medium', ['socialActivity', 'lastPost', 'accountRecency']);
export const _det830 = makeDet(830, '14.2', 'ClickFix / device-linking hijack detection', 'medium', ['clickFix', 'deviceLinkHijack', 'clickFixDetect']);
export const _det509 = makeDet(509, '15', 'Model poisoning detection', 'high', ['modelPoisoning', 'trainingDataPoison', 'poisonDetect']);
export const _det511 = makeDet(511, '15', 'Model inversion attack prevention', 'medium', ['modelInversion', 'inversionAttack', 'privacyAttack']);
export const _det514 = makeDet(514, '15', 'Model confidence calibration', 'medium', ['confidenceCalibration', 'calibrateModel', 'temperatureScaling']);
export const _det515 = makeDet(515, '15', 'Distribution shift detection', 'medium', ['distributionShift', 'dataShift', 'covariateDrift', 'driftDetect']);
export const _det520 = makeDet(520, '15', 'Detector efficacy metrics', 'medium', ['detectorEfficacy', 'precisionRecall', 'falsePositiveRate', 'efficacyMetrics']);
export const _det613 = makeDet(613, '15.1', 'Third-party AI data sharing detection', 'medium', ['thirdPartyAI', 'aiDataSharing', 'externalAISharing']);
export const _det615 = makeDet(615, '15.1', 'AI photo editing authenticity boundary', 'medium', ['aiPhotoEdit', 'editBoundary', 'aiEditLimit', 'photoEditAuthenticity']);
export const _det678 = makeDet(678, '15.2', 'AI-agent-to-AI-agent interaction detection', 'medium', ['agentToAgent', 'aiToAi', 'botToBotDetect']);
export const _det731 = makeDet(731, '15.3', 'AI conversation starter safety scan', 'medium', ['aiStarterSafety', 'conversationStarterScan', 'aiStarterModerate']);
export const _det734 = makeDet(734, '15.3', 'AI hallucination in platform-generated content', 'medium', ['aiHallucination', 'hallucinationDetect', 'factCheck']);
export const _det661 = makeDet(661, '15.5', 'Socioeconomic bias in profile visibility', 'medium', ['socioeconomicBias', 'visibilityBias', 'classBasedBias']);
export const _det792 = makeDet(792, '16.1', 'Age-gate circumvention detection', 'high', ['ageGateCircumvent', 'ageBypass', 'ageGateEvasion']);
export const _det585 = makeDet(585, '17', 'Cognitive load assessment', 'low', ['cognitiveLoad', 'simplifyUI', 'cognitiveAccessibility']);
export const _det606 = makeDet(606, '20', 'Compulsive usage / doom-swiping detection', 'medium', ['compulsiveUsage', 'doomSwiping', 'excessiveSwipe', 'sessionOveruse']);
export const _det608 = makeDet(608, '20', 'Rejection sensitivity overload detection', 'medium', ['rejectionOverload', 'rejectionSensitivity', 'massRejection']);
export const _det609 = makeDet(609, '20', 'Self-esteem impact monitoring', 'medium', ['selfEsteemImpact', 'wellbeingScore', 'mentalHealthImpact']);
export const _det735 = makeDet(735, '20', 'Algorithmic engagement vs wellbeing tradeoff', 'medium', ['engagementVsWellbeing', 'wellbeingTradeoff', 'engagementBalance']);
export const _det736 = makeDet(736, '20', 'Rejection overexposure throttling', 'medium', ['rejectionThrottle', 'rejectionOverexposure', 'throttleRejection']);
export const _det897 = makeDet(897, '20.1', 'Emotional fatigue intervention', 'medium', ['emotionalFatigue', 'fatigueIntervention', 'burnoutDetect']);
export const _det635 = makeDet(635, '22', 'Employer verification', 'medium', ['employerVerify', 'companyVerification', 'workVerify']);
export const _det751 = makeDet(751, '22', 'Body type misrepresentation reporting category', 'low', ['bodyMisrepresentation', 'bodyTypeReport', 'physicalMismatch']);
export const _det637 = makeDet(637, '23', 'Notification frequency abuse', 'medium', ['notificationAbuse', 'notificationFrequency', 'spamNotification']);
export const _det743 = makeDet(743, '23', 'Communication consent gate', 'medium', ['communicationConsent', 'messageConsent', 'consentToMessage']);
export const _det744 = makeDet(744, '23', 'Unsolicited video call blocking', 'medium', ['unsolicitedCall', 'videoCallBlock', 'callConsent']);
export const _det690 = makeDet(690, '23.1', 'Last online status obsessive checking', 'medium', ['lastOnlineStalking', 'onlineStatusObsessive', 'statusCheckAbuse']);
export const _det692 = makeDet(692, '23.1', 'Online status visibility granular controls', 'medium', ['statusVisibility', 'onlineVisibility', 'hideOnlineStatus']);
export const _det630 = makeDet(630, '24', 'VR identity verification', 'medium', ['vrIdentity', 'avatarVerification', 'vrRealPerson']);
export const _det670 = makeDet(670, '25', 'Wearable device data consent verification', 'medium', ['wearableConsent', 'deviceDataConsent', 'biometricDeviceConsent']);
export const _det671 = makeDet(671, '25', 'Biometric data collection limitation', 'medium', ['biometricCollection', 'heartRateLimit', 'biometricMinimization']);
export const _det675 = makeDet(675, '26', 'Group chat moderation', 'medium', ['groupChatModeration', 'multiPartyChat', 'groupDynamics']);
export const _det912 = makeDet(912, '26', 'Event organizer verification', 'medium', ['organizerVerify', 'eventOrganizerCheck', 'hostVerification']);
export const _det682 = makeDet(682, '27', 'Contact syncing hash-only verification', 'medium', ['contactHash', 'hashOnlySync', 'contactSyncHash']);
export const _det684 = makeDet(684, '27', 'People you may know leakage prevention', 'high', ['pymkLeakage', 'peopleYouMayKnow', 'pymkPrivacy']);
export const _det710 = makeDet(710, '29', 'Coercive partner account monitoring detection', 'high', ['coercivePartner', 'partnerMonitoring', 'accountSurveillance']);
export const _det711 = makeDet(711, '29', 'IPV risk assessment integration', 'high', ['ipvRisk', 'ipvAssessment', 'domesticViolence']);
export const _det712 = makeDet(712, '29', 'Forced account creation detection', 'high', ['forcedCreation', 'coercedSignup', 'forcedAccount']);
export const _det810 = makeDet(810, '29.1', 'Financial abuse language patterns', 'high', ['financialAbuse', 'moneyControl', 'financialCoercion']);
export const _det727 = makeDet(727, '30', 'Caretaker exploitation detection', 'high', ['caretakerExploitation', 'elderAbuse', 'caretakerAbuse']);
export const _det840 = makeDet(840, '31', 'Privacy-preserving identity verification', 'medium', ['privacyPreservingVerify', 'minimalVerification', 'privacyVerify']);
export const _det703 = makeDet(703, '33', 'Military / intelligence professional profile protection', 'high', ['militaryProtection', 'intelligenceProfile', 'milProfile']);
export const _det705 = makeDet(705, '33', 'Activist / journalist enhanced privacy mode', 'high', ['activistPrivacy', 'journalistProtection', 'enhancedPrivacy']);
export const _det760 = makeDet(760, '34', 'Accessibility-based scam vectors', 'medium', ['accessibilityScam', 'disabilityScam', 'a11yScamVector']);
export const _det764 = makeDet(764, '35', 'Interfaith exploitation pattern', 'medium', ['interfaithExploitation', 'religiousExploitation', 'faithExploit']);
export const _det804 = makeDet(804, '38', 'Customer support social engineering detection', 'high', ['supportSocialEng', 'socialEngineeringSupport', 'csSocialEngineering']);
export const _det858 = makeDet(858, '39', 'Anonymous account abuse detection', 'medium', ['anonAbuse', 'anonymousAbuse', 'throwawayAbuse']);
export const _det698 = makeDet(698, '42', 'Subscription cancellation friction audit', 'medium', ['cancellationFriction', 'cancelSubscription.*friction', 'easyCancel']);
export const _det756 = makeDet(756, '42', 'Premium feature weaponization detection', 'medium', ['premiumWeaponization', 'featureWeaponize', 'premiumAbuse']);
export const _det895 = makeDet(895, '43', 'Safety feature usage analytics', 'medium', ['safetyUsageAnalytics', 'featureUsageTracking', 'safetyAdoption']);
export const _det641 = makeDet(641, '44', 'Account selling / marketplace detection', 'medium', ['accountSellingDetect', 'accountMarketplaceDetect', 'sellAccount']);
export const _det642 = makeDet(642, '44', 'Premium feature exploitation for harassment', 'medium', ['premiumHarassment', 'featureExploit.*harass', 'premiumHarassAbuse']);