import { StyleSheet } from 'react-native-unistyles';

export const s = StyleSheet.create((theme) => ({
  container:        { flex: 1, backgroundColor: theme.colors.background },
  flex:             { flex: 1 },
  loadingContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: { fontSize: 14, color: theme.colors.textSecondary },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.background,
  },
  headerBack:         { padding: 4 },
  headerTitle:        { flex: 1, fontSize: 18, fontWeight: '800', color: theme.colors.text, textAlign: 'center' },
  headerSave:         { paddingVertical: 6, paddingHorizontal: 16, borderRadius: 10 },
  headerSaveDisabled: { opacity: 0.5 },
  headerSaveText:     { fontSize: 15, fontWeight: '700', color: theme.colors.primary },

  scrollContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 60 },

  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },

  photoSection:     { marginBottom: 28 },
  photoGrid:        { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  photoCell:        { width: '31%', aspectRatio: 3 / 4, borderRadius: 14, overflow: 'hidden' },
  photoImage:       { width: '100%', height: '100%', borderRadius: 14, borderWidth: 2, borderColor: 'transparent' },
  photoPrimary:     { borderColor: theme.colors.primary, borderWidth: 2 },
  primaryBadge:     {
    position: 'absolute',
    bottom: 6,
    left: 6,
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  primaryBadgeText: { fontSize: 9, fontWeight: '700', color: '#fff' },
  photoIndexBadge:  {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.5)',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoIndexText:   { fontSize: 10, fontWeight: '700', color: '#fff' },
  photoAddCell:     {
    width: '31%',
    aspectRatio: 3 / 4,
    borderRadius: 14,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  photoAddText:     { fontSize: 12, color: theme.colors.primary, fontWeight: '600' },
  photoActions:     { flexDirection: 'row', gap: 12, marginTop: 12 },
  photoActionBtn:   {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  photoActionText:  { fontSize: 13, color: theme.colors.primary, fontWeight: '600' },

  fieldSection:       { marginBottom: 24 },
  inputWrap:          {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 14,
    minHeight: 48,
  },
  inputWrapError:     { borderColor: theme.colors.error },
  inputWrapMultiline: { alignItems: 'flex-start', paddingVertical: 12 },
  inputIcon:          { marginRight: 10, marginTop: 2 },
  input:              { flex: 1, fontSize: 15, color: theme.colors.text, paddingVertical: 12 },
  inputPlaceholder:   { color: theme.colors.textSecondary },
  inputMultiline:     { minHeight: 100, maxHeight: 150, lineHeight: 20, paddingVertical: 0 },
  fieldError:         { fontSize: 12, color: theme.colors.error, marginTop: 6, marginLeft: 2 },
  fieldHint:          { fontSize: 11, color: theme.colors.textSecondary, textAlign: 'right', marginTop: 4 },

  toggleRow:   {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  toggleInfo:  { flex: 1, marginRight: 16 },
  toggleLabel: { fontSize: 15, fontWeight: '600', color: theme.colors.text },
  toggleDesc:  { fontSize: 12, color: theme.colors.textSecondary, marginTop: 2 },

  bottomSpacer: { height: 40 },

  photoPreviewOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(4,4,12,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  photoPreviewCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 380,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 16,
    alignItems: 'center',
  },
  photoPreviewTitle:           { fontSize: 18, fontWeight: '800', color: theme.colors.text },
  photoPreviewImage:           { width: '100%', aspectRatio: 3 / 4, borderRadius: 14 },
  photoPreviewBtns:            { flexDirection: 'row', gap: 12, width: '100%' },
  photoPreviewCancel:          {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  photoPreviewCancelText:      { fontSize: 14, fontWeight: '600', color: theme.colors.textSecondary },
  photoPreviewConfirm:         {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
  },
  photoPreviewConfirmDisabled: { backgroundColor: theme.colors.surface },
  photoPreviewConfirmText:     { fontSize: 14, fontWeight: '700', color: '#fff' },

  deleteOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(4,4,12,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  deleteCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 360,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 12,
    alignItems: 'center',
  },
  deleteTitle:       { fontSize: 18, fontWeight: '800', color: theme.colors.text },
  deleteSub:         { fontSize: 14, color: theme.colors.textSecondary, textAlign: 'center' },
  deleteBtns:        { flexDirection: 'row', gap: 12, width: '100%', marginTop: 4 },
  deleteCancel:      {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  deleteCancelText:  { fontSize: 14, fontWeight: '600', color: theme.colors.textSecondary },
  deleteConfirm:     {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: theme.colors.error,
    alignItems: 'center',
  },
  deleteConfirmText: { fontSize: 14, fontWeight: '700', color: '#fff' },

  genderOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(4,4,12,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  genderCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 360,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 8,
  },
  genderTitle:              { fontSize: 18, fontWeight: '800', color: theme.colors.text, marginBottom: 8 },
  genderOption:             {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  genderOptionSelected:     { borderColor: theme.colors.primary, backgroundColor: 'rgba(108,99,255,0.08)' },
  genderOptionText:         { fontSize: 15, color: theme.colors.text },
  genderOptionTextSelected: { fontWeight: '600', color: theme.colors.primary },
  genderCancel:             { paddingVertical: 14, alignItems: 'center', marginTop: 8 },
  genderCancelText:         { fontSize: 14, color: theme.colors.textSecondary, fontWeight: '600' },
}));