import { StyleSheet } from 'react-native-unistyles';
import { IS_IOS } from './constants';

export const s = StyleSheet.create({
  rootBg:        { flex: 1 },
  safe:          { flex: 1 },
  container:     { flex: 1 },
  fill:          { flex: 1 },
  absoluteFill:  { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  scrollContent: { flexGrow: 1, justifyContent: 'center', paddingBottom: 52 },
  content:       { width: '100%', alignSelf: 'center' },
  headerContainer: { alignItems: 'center' },
  logoOuter:     { width: 84, height: 84, alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  logoCircle:    { width: 76, height: 76, borderRadius: 38, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5 },
  title:         { fontWeight: '800', marginBottom: 10, letterSpacing: -0.5, textAlign: 'center' },
  subtitle:      { textAlign: 'center', lineHeight: 24, letterSpacing: 0.1 },
  lockoutBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 14, borderWidth: 1, marginBottom: 20 },
  lockoutText:   { fontSize: 13, fontWeight: '600', flex: 1 },
  formCard:      { borderRadius: 24, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.2, shadowRadius: 28, elevation: 14 },
  inputContainer: { marginBottom: 26 },
  inputLabel:    { fontSize: 13, fontWeight: '600', marginBottom: 10, marginLeft: 2, letterSpacing: 0.15 },
  inputWrapper:  { flexDirection: 'row', alignItems: 'center', borderRadius: 14, borderWidth: 1.5, paddingHorizontal: 16, minHeight: 58, shadowOffset: { width: 0, height: 0 }, shadowRadius: 14, elevation: 4 },
  inputWrapperFocused: {},
  inputIcon:     { marginRight: 14, width: 22, textAlign: 'center' },
  inputNative:   { flex: 1, fontSize: 16, paddingVertical: IS_IOS ? 18 : 15, letterSpacing: 0.2, backgroundColor: 'transparent' },
  eyeButton:     { padding: 8, marginLeft: 4, borderRadius: 20 },
  capsLockRow:   { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 10, borderRadius: 10, borderWidth: 1, marginBottom: 12, marginTop: -12 },
  capsLockText:  { fontSize: 12, fontWeight: '600' },
  errorRow:      { flexDirection: 'row', alignItems: 'center', marginTop: 8, marginLeft: 2, gap: 6 },
  errorText:     { fontSize: 12, fontWeight: '500', flex: 1 },
  forgotRow:     { alignSelf: 'flex-end', paddingVertical: 8, paddingHorizontal: 4, marginTop: -8, marginBottom: 8 },
  forgotText:    { fontSize: 13, fontWeight: '600' },
  buttonSpacer:  { height: 8 },
  buttonOuter:   { width: '100%', borderRadius: 16, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.45, shadowRadius: 20, elevation: 12 },
  gradientButtonInner: { borderRadius: 16 },
  button:        { paddingVertical: 20, borderRadius: 16, alignItems: 'center', justifyContent: 'center', minHeight: 62 },
  buttonDisabled: { shadowOpacity: 0, elevation: 0 },
  buttonContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  buttonText:    { color: '#ffffff', fontSize: 17, fontWeight: '700', letterSpacing: 0.3 },
  footer:        { alignItems: 'center', marginTop: 36, gap: 0, paddingHorizontal: 16 },
  resendButton:  { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 14, paddingHorizontal: 20, borderRadius: 14, borderWidth: 1 },
  resendText:    { fontSize: 14, fontWeight: '600' },
  separatorRow:  { flexDirection: 'row', alignItems: 'center', marginVertical: 28, width: '100%' },
  separatorLine: { flex: 1, height: StyleSheet.hairlineWidth },
  separatorText: { fontSize: 13, marginHorizontal: 16, fontWeight: '600', letterSpacing: 0.5 },
  signUpButton:  { paddingVertical: 12, paddingHorizontal: 24 },
  signUpText:    { fontSize: 15, lineHeight: 22 },
  signUpLink:    { fontWeight: '700' },
  loadingOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', zIndex: 10 },
  loadingCard:   { borderRadius: 24, padding: 40, alignItems: 'center', gap: 20, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 16, minWidth: 200 },
  loadingText:   { fontSize: 15, fontWeight: '500' },
  successOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', zIndex: 20 },
  successCard:   { borderRadius: 28, padding: 48, alignItems: 'center', gap: 16, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.4, shadowRadius: 24, elevation: 20 },
  successIconCircle: { width: 92, height: 92, borderRadius: 46, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  successTitle:  { fontSize: 26, fontWeight: '800', letterSpacing: -0.3 },
  successSub:    { fontSize: 15, fontWeight: '500', textAlign: 'center', lineHeight: 22 },
  modalOverlay:  { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', zIndex: 30, padding: 24 },
  modalCard:     { width: '100%', maxWidth: 400, borderRadius: 22, padding: 30, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.4, shadowRadius: 24, elevation: 24, gap: 16 },
  modalTitle:    { fontSize: 19, fontWeight: '800', letterSpacing: -0.2 },
  modalMessage:  { fontSize: 14, lineHeight: 23 },
  modalButtons:  { flexDirection: 'row', gap: 10, marginTop: 10, justifyContent: 'flex-end', flexWrap: 'wrap' },
  modalButton:   { paddingVertical: 11, paddingHorizontal: 22, borderRadius: 11, borderWidth: 1 },
  modalButtonText: { fontSize: 14 },
  errorFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 16 },
  errorFallbackTitle: { fontSize: 22, fontWeight: '800', textAlign: 'center' },
  errorFallbackSub:   { fontSize: 15, textAlign: 'center', lineHeight: 22 },
  retryButton:   { marginTop: 8, paddingVertical: 12, paddingHorizontal: 28, borderRadius: 12, borderWidth: 1.5 },
  retryText:     { fontSize: 15, fontWeight: '700' },
});